from django.db import models

# Create your models here.

class patient_info(models.Model):
    id = models.AutoField(primary_key=True)
    rank = models.TextField(max_length=20)
    last_name = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50)
    serial_number = models.IntegerField(max_length=6)
    bos = models.TextField(max_length=50)
    unit = models.TextField(max_length=50)
    birthday = models.CharField(max_length=255)
    age = models.IntegerField(max_length=2)
    gender = models.CharField(max_length=50)
    contact_number = models.IntegerField(max_length=15)
    region = models.TextField(max_length=50)
    province = models.TextField(max_length=100)
    municipality = models.CharField(max_length=100)
    barangay = models.CharField(max_length=100)
    purok = models.CharField(max_length=100)
    vaccinated = models.TextField(max_length=5)
    brand_vaccine = models.TextField(max_length=100)
    first_dose_date = models.CharField(max_length=100)
    second_dose_date = models.CharField(max_length=100)
    prioritization = models.TextField(max_length=10)
    spouse_name = models.TextField(max_length=255)
    mothers_name = models.TextField(max_length=255)
    fathers_name = models.TextField(max_length=255)
    #test_type = models.TextField(max_length=100)
    #test_reason = models.TextField(max_length=255)
    #test_date = models.CharField(max_length=100)
    #test_kit_brand = models.CharField(max_length=100) 